import type { Metadata } from "next";
import "../styles/globals.css";
import { hankenGrotesk, inter, jetBrainsMono } from "@/lib/font";
import { JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        hankenGrotesk.className,
        jetBrainsMono.variable,
        hankenGrotesk.variable,
        inter.variable,
        "font-mono",
      )}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
